<?php
session_start();

// Database connection details
$servername = "localhost";
$username = "root";
$password = "surayya"; // Replace with your actual MySQL password
$dbname = "cyberlearn";

// Create connection
$conn = mysqli_connect($servername, $username, $password, $dbname);

// Check connection
if (!$conn) {
    die("Connection failed: " . mysqli_connect_error());
}

// Initialize variable
$registered_modules = [];

// Fetch user's registered modules from database
$user_id = $_SESSION['user_id'] ?? 0;
if ($user_id > 0) {
    $sql = "SELECT module.module_id, module.module_name, module.description
            FROM user_module
            INNER JOIN module ON user_module.module_id = module.module_id
            WHERE user_module.user_id = ?";

    $stmt = mysqli_prepare($conn, $sql);
    mysqli_stmt_bind_param($stmt, "i", $user_id);
    mysqli_stmt_execute($stmt);
    $result = mysqli_stmt_get_result($stmt);

    if (mysqli_num_rows($result) > 0) {
        while ($row = mysqli_fetch_assoc($result)) {
            $registered_modules[] = [
              'module_id' => $row['module_id'],
              'module_name' => htmlspecialchars($row['module_name']),
              'description' => htmlspecialchars($row['description'])
          ];
        }
    }

    mysqli_stmt_close($stmt);
}

mysqli_close($conn);
?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>User Dashboard - CyberLearn</title>
  <link rel="stylesheet" href="main.css">
</head>
<body>
  <div class="container">
    <h1 class="gradient-title">Welcome, <?php echo htmlspecialchars($_SESSION['username']); ?>!</h1>
    <div class="search-box">
      <input type="text" placeholder="Search courses, quizzes, activities...">
    </div>
    <div class="content-section">
      <div class="category">
        <h2>Courses Enrolled</h2>
        <ul>
        <?php
          if (!empty($registered_modules)) {
              foreach ($registered_modules as $module) {
                  // Assuming the HTML file name is generated by replacing spaces with underscores and converting to lowercase
                  $htmlFileName = strtolower(str_replace(' ', '-', $module['module_name'])) . ".html";
                  echo '
                  <div class="grid">
                    <div class="grid-header">
                      <div class="icon">
                        <i class="fas fa-book"></i>
                      </div>
                      <div class="label">
                        <a href="' . htmlspecialchars($htmlFileName) . '">' . htmlspecialchars($module['module_name']) . '</a>
                      </div>
                    </div>
                    <div class="grid-body">
                      <div class="course-info">
                        <p>Progress: 0%</p>
                        <div class="progress-bar">
                          <div class="progress" style="width: 0%;"></div>
                        </div>
                      </div>
                    </div>
                  </div>';
              }
          } else {
              echo '<p>No modules registered yet.</p>';
          }
          ?>
        </ul>
      </div>
      <div class="category">
        <h2>Quizzes</h2>
        <ul>
          <!-- Add quiz links here -->
          <li>Quiz 1</li>
          <li>Quiz 2</li>
          <li>Quiz 3</li>
        </ul>
      </div>
      <div class="category">
        <h2>Activities</h2>
        <ul>
          <!-- Add activity links here -->
          <li>Activity 1</li>
          <li>Activity 2</li>
          <li>Activity 3</li>
        </ul>
      </div>
      <div class="category">
        <h2>To-Do List</h2>
        <ul>
          <!-- Add to-do items here -->
          <li>To-Do Item 1</li>
          <li>To-Do Item 2</li>
          <li>To-Do Item 3</li>
        </ul>
      </div>
    </div>
    <div class="navigation">
      <a href="register-courses.php" class="button">Register for Courses</a>
      <a href="logout.php" class="button">Log Out</a>
    </div>
  </div>

  <script>
    function openChat() {
      document.getElementById('chatbot-modal').style.display = 'block';
    }

    function closeChat() {
      document.getElementById('chatbot-modal').style.display = 'none';
    }
  </script>

  <!-- Chatbot Icon -->
  <div class="chatbot-container">
    <img src="phantom.jpeg" class="chatbot-icon" width="50" height="50" onclick="openChat()">
  </div>

  <!-- Chatbot Modal -->
  <div id="chatbot-modal" class="chatbot-modal">
    <span class="close-btn" onclick="closeChat()">×</span>
    <iframe src="chatbot.html"></iframe>
  </div>
</body>
</html>


